# spec file for package postgresql18-osml10n
#
# rules v.1.0
#
# Copyright (c) 2026 RED SOFT
#
# The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package
# itself (unless the license for the package is not an
# Open Source License, in which case the license is the MIT License).

%if 0%{redos_version} < 0800
%global _lto_cflags %{nil}
%endif

%global pg_bindir /usr/pgsql-18/bin
%global pg_config %{pg_bindir}/pg_config
%global pg_sharedir %( %{pg_config} --sharedir )
%global pg_pkglibdir %( %{pg_config} --pkglibdir )
%global pg_includedir_server %( %{pg_config} --includedir-server )

Name:           postgresql18-osml10n
Summary:        Localization functions for OpenStreetMap (osml10n)
URL:            https://github.com/nekamsk/postgresql18-osml10n
License:        AGPL-3.0-or-later
Epoch:          0
Version:        2.5.10
Release:        1%{?dist}
VCS:            https://github.com/nekamsk/postgresql18-osml10n.git

Source0:        postgresql18-osml10n.tar.gz
Source1:        country_grid.sql.gz

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  curl
BuildRequires:  gzip
BuildRequires:  libicu-devel
BuildRequires:  kakasi-devel
BuildRequires:  utf8proc-devel
BuildRequires:  postgresql18-devel
BuildRequires:  pandoc

Requires:       postgresql18 >= 18.4
Requires:       postgresql18-contrib
Requires:       postgresql18-plpython3
Requires:       postgis-pgsql-18
Requires:       kakasi-libs
Requires:       kakasi-dict

%description
OSM map localization functions originally developed for the German Mapnik
style. The localization functions are implemented as PostgreSQL stored
procedures and can therefore be used independently of a particular renderer.

The extension contains an Any-Latin transliteration function using ICU,
a Japanese kanji transcription function using libkakasi, and PL/pgSQL
functions for generating localized labels from OpenStreetMap data.

The package also contains the separate osml10n_thai_transcript extension,
which provides Thai transcription through plpython3u and the TLTK Python
package when TLTK is available.

%prep
%setup -q -n postgresql18-osml10n

gzip -dc %{SOURCE1} > country_osm_grid.sql

%build
export PATH=%{pg_bindir}:$PATH
export PG_CONFIG=%{pg_config}

# country_languages.data is generated by the original Makefile
# from country_languages.data.in.
make country_languages.data

# Build the PostgreSQL loadable modules.
make -C kanjitranscript CC=gcc \
  'CFLAGS=%{optflags}' \
  'LDFLAGS=%{build_ldflags}'

make -C icutranslit CXX=g++ \
  'CXXFLAGS=%{optflags}' \
  'LDFLAGS=%{build_ldflags}'

# Generate the current extension SQL files.
./gen_osml10n_extension.sh %{pg_sharedir}/extension %{version}
./gen_osml10n_thai_extension.sh %{pg_sharedir}/extension %{version}

# Generate extension control files.
sed -e "s/VERSION/%{version}/g" \
    osml10n.control.in > osml10n.control

sed -e "s/VERSION/%{version}/g" \
    osml10n_thai_transcript.control.in > osml10n_thai_transcript.control

# Generate upgrade scripts corresponding to the original Makefile.
# The previous version is taken from debian/changelog by the upstream
# Makefile; for the 2.5.10 source this is 2.5.9.
tail -n +3 osml10n--%{version}.sql \
    > osml10n--2.5.9--%{version}.sql

tail -n +3 osml10n_thai_transcript--%{version}.sql \
    > osml10n_thai_transcript--2.5.9--%{version}.sql

%install
mkdir -p %{buildroot}%{pg_pkglibdir}
mkdir -p %{buildroot}%{pg_sharedir}/extension

install -m 0755 \
    kanjitranscript/osml10n_kanjitranscript.so \
    %{buildroot}%{pg_pkglibdir}/osml10n_kanjitranscript.so

install -m 0755 \
    icutranslit/osml10n_translit.so \
    %{buildroot}%{pg_pkglibdir}/osml10n_translit.so

install -m 0644 \
    osml10n.control \
    %{buildroot}%{pg_sharedir}/extension/osml10n.control

install -m 0644 \
    osml10n--*.sql \
    %{buildroot}%{pg_sharedir}/extension/

install -m 0644 \
    osml10n_country_osm_grid.data \
    %{buildroot}%{pg_sharedir}/extension/osml10n_country_osm_grid.data

install -m 0644 \
    osml10n_thai_transcript.control \
    %{buildroot}%{pg_sharedir}/extension/osml10n_thai_transcript.control

install -m 0644 \
    osml10n_thai_transcript--*.sql \
    %{buildroot}%{pg_sharedir}/extension/

install -m 0644 \
    country_languages.data \
    %{buildroot}%{pg_sharedir}/extension/country_languages.data

%check
# Generated control files.
test -s osml10n.control
test -s osml10n_thai_transcript.control

# Current extension SQL files.
test -s osml10n--%{version}.sql
test -s osml10n_thai_transcript--%{version}.sql

# Upgrade SQL files.
test -s osml10n--2.5.9--%{version}.sql
test -s osml10n_thai_transcript--2.5.9--%{version}.sql

# Runtime data files.
test -s osml10n_country_osm_grid.data
test -s country_languages.data

# PostgreSQL loadable modules.
test -s kanjitranscript/osml10n_kanjitranscript.so
test -s icutranslit/osml10n_translit.so

# Shell syntax.
bash -n gen_osml10n_extension.sh
bash -n gen_osml10n_thai_extension.sh

# Basic validation of generated SQL.
grep -q '\$libdir/osml10n_kanjitranscript' \
    osml10n--%{version}.sql

grep -q '\$libdir/osml10n_translit' \
    osml10n--%{version}.sql

grep -q 'osml10n_country_osm_grid.data' \
    osml10n--%{version}.sql

grep -q 'country_languages.data' \
    osml10n--%{version}.sql

grep -q 'osml10n_version' \
    osml10n--%{version}.sql

%files
%license LICENSE.txt
%doc README.md INSTALL.md

%{pg_pkglibdir}/osml10n_kanjitranscript.so
%{pg_pkglibdir}/osml10n_translit.so

%{pg_sharedir}/extension/osml10n.control
%{pg_sharedir}/extension/osml10n--*.sql
%{pg_sharedir}/extension/osml10n_country_osm_grid.data

%{pg_sharedir}/extension/country_languages.data

%{pg_sharedir}/extension/osml10n_thai_transcript.control
%{pg_sharedir}/extension/osml10n_thai_transcript--*.sql

%changelog
* Mon Sep 28 2026 nekamsk - 2.5.10-1
- Make this build for RPM package manager and PostgreSQL 18
